Web/urls.py
from django.contrib import admin
from django.urls import path,include
from Web import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('user.urls','user'),namespace='user')),
    path('',include(('product.urls','product'),namespace='product')),
    path('',include(('cart.urls','cart'),namespace='cart')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crt/<str:p_id>',v.cart_view,name='crt'),
    path('cart_list',v.Cart_list,name='cart_list'),
    path('delete/<int:id>',v.Delete_view,name='delete'),
    path('order_list',v.Order_List_view,name='order_list'),
    path('delete_pro/<int:id>',v.Delete_pro,name='delete_pro'),
    path('about-us',v.About_view,name='about-us'),
    
   
]

product/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product',v.product_view,name='product'),
    path('srh',v.Search_view,name='srh'),
    path('buy_order/<str:p_id>',v.Buy_oeder_view,name='buy_order'),
    path('make_pay/<str:p_id>',v.Make_payment,name='make_pay'),
    path('sucess',v.Sucess,name='sucess')
]

user/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',v.home),
    path('sineup',v.Resister,name='sineup'),
    path('login',v.login_view,name='login'),
    path('logout',v.logout_view,name='logout'),
    path('profile',v.profile_view,name='profile'),
    path('show_profile',v.Profile_show),
    path('update/<int:pk>',v.update.as_view()),
   
    
]

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms

# Create your models here.


class Catagory(models.Model):
    cat_img=models.ImageField(upload_to='amit')
    name=models.CharField(max_length=40)
    desc1=models.TextField(default='')

    class Meta:
        db_table='catagory'

    def __str__(self):
        return self.name
    @staticmethod
    def get_all_cat():
        return Catagory.objects.all()




class Product(models.Model):
    catagory=models.ForeignKey(Catagory,on_delete=models.CASCADE)
    pro_img=models.ImageField(upload_to='amit')
    pro_name=models.CharField(max_length=40)
    price=models.IntegerField()
    desc=models.TextField()

    class Meta:
        db_table='product'

    
    def __str__(self):
        return self.pro_name
    @staticmethod
    def get_all_pro():
        return Product.objects.all()
    
    @staticmethod
    def get_data_id(catagory_id):
        if catagory_id:
           return Product.objects.filter(catagory=catagory_id)
        else:
           return Product.get_all_pro()
    



class Product_order_buy(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    email=models.EmailField()
    contact=models.CharField(max_length=50)
    address=models.TextField()
    quantity=models.IntegerField(default=1)
    ord_date=models.DateField(auto_now=True)
    status=models.BooleanField(default=False)

    class Meta:
        db_table='buy_product'

class Pro_buy_Form(forms.ModelForm):
    class Meta:
        model=Product_order_buy
        fields=['email','contact','address','quantity']


class Order_Payment(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    email=models.EmailField()
    amount=models.CharField(max_length=100)
    payment_id=models.CharField(max_length=100)
   

    class Meta:
        db_table='pay_order'

user/models.py
from django.db import models

from django import forms
from django.contrib.auth.models import User


# Create your models here.

class LogForm(forms.Form):
    usernema=forms.CharField(max_length=30)
    password=forms.CharField(max_length=40)



class Profile(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    profile_pic=models.ImageField(upload_to='amit')
    first_name=models.CharField(max_length=70)
    Last_name=models.CharField(max_length=70)
    dob=models.DateField(max_length=70)
    email=models.EmailField(max_length=70)
    address=models.TextField()

    class Meta:
        db_table='profile'



class Pr_Form(forms.ModelForm):
    class Meta:
        model=Profile
        fields='__all__'   



    

   
    
    

user/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login,logout,authenticate
from .models import LogForm
from django.contrib.auth.models import User
from product.models import Catagory,Product
from django.views.generic import CreateView,FormView,UpdateView,DeleteView,TemplateView
from django.contrib import messages

from .models import Pr_Form,Profile

# Create your views here.


def home(request):
    catagorys=Catagory.get_all_cat()
    products=Product.get_all_pro()
    catagory_id=request.GET.get('catagory')
    if catagory_id:
       products=Product.get_data_id(catagory_id)
    else:
        Product.get_all_pro()
   
    data={}
    data['dt']=products
    data['cta']=catagorys
    
    return render(request,'home.html',data)

def Resister(request):
    if request.method=='POST':
        fr=UserCreationForm(request.POST)
        fr.save()
        # messages.success(request,'Your Profile Has Been Resister Sucessfully') 
        return redirect('/')
       
    else:
        form=UserCreationForm()
        context={'form':form}
        messages.warning(request,'Some thing Went Wrong Please Check!') 
        return render(request,'sineup.html',context)
    


def login_view(request):
    if request.method=='POST':
        uname=request.POST.get('username')
        pasw=request.POST.get('password')
        user=authenticate(User,username=uname,password=pasw)
        
        if user is not None:
            request.session['uid']=user.id
            login(request,user)
            messages.success(request,'You Have Login Sucessfully') 
            return redirect('/')
        else:
            lo=LogForm()
            data={'form':lo}
            messages.warning(request,'Some thing Went Wrong Please Check Username And Password!') 
            return render(request,'login.html',data)

    else:
        lo=LogForm()
        data={'form':lo}
        return render(request,'login.html',data)



def logout_view(request):
    logout(request)
    messages.success(request,'You Have Logout Sucessfully') 
    return redirect('/')


def profile_view(request):
    upid=request.session.get('uid')
    user=User.objects.get(id=upid)
    if request.method=='POST':
        img=request.POST.get('profile_pic')
        f_n=request.POST.get('first_name')
        l_n=request.POST.get('Last_name')
        em=request.POST.get('email')
        dob=request.POST.get('dob')
        add=request.POST.get('address')

        pf=Profile()
        pf.profile_pic=img
        pf.first_name=f_n
        pf.Last_name=l_n
        pf.email=em
        pf.dob=dob
        pf.address=add
        pf.user=user
        pf.save()
        messages.success(request,'Your Profile Created Sucessfully') 
        return redirect('/')
        
    else:
        fr=Pr_Form()
        fe={'form':fr}
        return render(request,'profile.html',fe)
    

def Profile_show(request):
    upid=request.session.get('uid')
    user=User.objects.get(id=upid)
    list_pro=Profile.objects.filter(user=upid)
    data={'list':list_pro}
    return render(request,'tt.html',data)


class update(UpdateView):
    model=Profile
    fields=['first_name','Last_name','email','address']
    template_name='update.html'
    success_url='/'

    


    

user/templates/foot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {%load static%}
    <link rel="stylesheet" href="{%static 'css/bmin.css'%}">
</head>
<body>
    <footer style="bottom: 0%;"    class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top bg-dark">
        <p class="col-md-4 mb-0 text-muted">© 2021 AmIsTrEeT, Inc</p>
    
        <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="90"><use xlink:href="#bootstrap"></use></svg>
        </a>
    
        <ul class="nav col-md-4 justify-content-end">
            
          <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Contact-us</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
        </ul>
        
      </footer>
</body>
</html>

user/templates/nav.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {%load static%}
    <link rel="stylesheet" href="{%static 'css/bmin.css'%}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">

            <a class="navbar-brand" href="#">AmIsTrEeT</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            {%if user.is_authenticated%}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    
                    <li class="nav-item">
                        <a class="nav-link " aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'product:product' %}">Store</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'cart:cart_list'%}">Cart
                            
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'cart:about-us'%}">About-us</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'cart:order_list'%}">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                    </li>

                    <li class="nav-item" >
                        <a class="nav-link" href="show_profile">Profile
                           
                              
                        </a>
                    </li>

                    {%else%}
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" href="{%url 'product:product' %}">Store</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'user:sineup' %}">Sineup</a>

                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">About-us</a>
                            </li>
                        </ul>
                    </div>
                    {%endif%}


                </ul>


            </div>
        </div>
    </nav>
</body>

</html>

user/templates/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>

</head>

<body>
    {%include 'nav.html'%}
   
    <h2 style="text-align: center;margin-top: 60px;">Profile Form</h2>
    <form action="" method="post" style="margin-top: 20px;">
        {%csrf_token%}
        <table class="d-flex justify-content-center align-items-center my-2 m">
            <tbody>
                <tr>
                </tr>
                <tr>
                    <th><label for="id_user" class="form-label">Username:</label></th>
                    <td>

                        <input type="text" class="form-control" name="user" class="form-control" required=""
                            id="id_user" fdprocessedid="67bbs" value="{{user}}">

                    </td>
                </tr>

                <tr>
                    <th><label for="id_profile_pic" class="form-label">Profile pic:</label></th>
                    <td>

                        <input type="file" class="form-control" name="profile_pic" accept="image/*" required=""
                            id="id_profile_pic">


                    </td>
                </tr>

                <tr>
                    <th><label for="id_first_name" class="form-label">First name:</label></th>
                    <td>

                        <input type="text" class="form-control" name="first_name" maxlength="70" required=""
                            id="id_first_name" fdprocessedid="ua23p">


                    </td>
                </tr>

                <tr>
                    <th><label for="id_Last_name" class="form-label">Last name:</label></th>
                    <td>

                        <input type="text" class="form-control" name="Last_name" maxlength="70" required=""
                            id="id_Last_name" fdprocessedid="r06wp4">


                    </td>
                </tr>

                <tr>
                    <th><label for="id_dob" class="form-label">Dob:</label></th>
                    <td>

                        <input type="text" class="form-control" name="dob" required="" id="id_dob"
                            fdprocessedid="g1icql">


                    </td>
                </tr>

                <tr>
                    <th><label for="id_email" class="form-label">Email:</label></th>
                    <td>

                        <input type="email" class="form-control" name="email" maxlength="70" required="" id="id_email"
                            fdprocessedid="fp5c8u">


                    </td>
                </tr>

                <tr>
                    <th><label for="id_address" class="form-label">Address:</label></th>
                    <td>

                        <input type="text" name="address" class="form-control" cols="40" rows="10" required=""
                            id="id_address">




                    </td>
                </tr>
                <tr>
                    <td>
                
                        <a href="/" class="btn btn-outline-danger  btn-lg  " tabindex="-1" role="button"
                            aria-disabled="true">Already Created</a>
                    </td>
                    <td>
                
                        <button type="submit" value="submit" class=" btn-outline-success my-4  btn-lg" style="margin-left: 30px;">Save Profile</button>
                    </td>
                
                </tr>

            </tbody>
        </table>
    </form>
    
</body>

</html>

user/templates/store.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store</title>
    {%load static%}
    <link rel="stylesheet" href="{%static 'css/bmin.css'%}">
</head>

<body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">AmIsTrEeT</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            {%if user.is_authenticated%}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link " aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'product:product' %}">Store</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'cart:cart_list'%}">Cart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'cart:about-us'%}">About-us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'cart:order_list'%}">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="show_profile">Profile


                        </a>
                    </li>
                    {%else%}
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link " aria-current="page" href="/">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{%url 'product:product' %}">Store</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'user:sineup' %}">Sineup</a>

                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">About-us</a>
                            </li>
                        </ul>
                    </div>
                    {%endif%}


                </ul>
                <form class="d-flex" action="srh" method="post">
                    {%csrf_token%}
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="srha">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path
                d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
        </symbol>
        <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
            <path
                d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
        </symbol>
        <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path
                d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </symbol>
    </svg>
    {%if messages%}
    {%for i in messages%}
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:">
            <use xlink:href="#check-circle-fill" />
        </svg>
        <div>
            {{i}}
        </div>
    </div>
    {%endfor%}
    {%endif%}



    <div class="container">
        <h2 style="background-color: rgb(6, 5, 5); color: rgb(135, 135, 76);text-align: center;height: 45px;">
            Product Catagory
        </h2>

        <div class="row row-cols-1 row-cols-md-2 g-4">
            <div class="col">
                <div class="card">

                    <div class="card-body">
                        <a href="/product" class="btn btn-danger btn-lg">

                            All
                        </a>

                    </div>
                </div>
            </div>
            {%for i in cta%}
            <div class="col">
                <div class="card">

                    <div class="card-body">
                        <a href="/product?catagory={{i.id}}" class="btn btn-outline-info btn-lg">

                            <h3 class="card-title">{{i.name}}</h3>
                        </a>

                    </div>
                </div>
            </div>
            {%endfor%}

        </div>
    </div>

    <div class="container">
        <h2 style="background-color: rgb(6, 5, 5); color: rgb(135, 135, 76);text-align: center;height: 45px;">
            Here Your Product
        </h2>

        <div class="row row-cols-1 row-cols-md-2 g-4">
            {%for i in dt%}
            <div class="col">
                <div class="card">
                    <img src="{{i.pro_img.url}}" height="250" width="300" class="img-fluid" alt="...">
                    <div class="card-body">
                        <h2 class="card-title">Rs.{{i.price}}</h2>
                        <h3 class="card-title">{{i.pro_name}}</h3>
                        <p class="card-text">{{i.desc}}</p>
                        {%if user.is_authenticated%}
                        <form action="" method="post">
                            {%csrf_token%}

                            <a href="{%url 'cart:crt' i.id %}" class="btn btn-outline-info btn-lg">

                                <h3 class="card-title">Add To Cart</h3>

                            </a>

                            <a href="{%url 'product:buy_order' i.id %}" class="btn btn-outline-warning btn-lg">

                                <h3 class="card-title">Buy</h3>
                        </form>

                        </a>
                        {%endif%}


                    </div>
                </div>
            </div>
            {%endfor%}

        </div>
    </div>

    {%include 'foot.html'%}
</body>

</html>

<form class="d-flex" action="srh" method="post">
                    {%csrf_token%}
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="srha">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path
                d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
        </symbol>
        <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
            <path
                d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z" />
        </symbol>
        <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path
                d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </symbol>
    </svg>
    {%if messages%}
    {%for i in messages%}
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:">
            <use xlink:href="#check-circle-fill" />
        </svg>
        <div>
            {{i}}
        </div>
    </div>
    {%endfor%}
    {%endif%}



    <div class="container">
        <h2 style="background-color: rgb(6, 5, 5); color: rgb(135, 135, 76);text-align: center;height: 45px;">
            Product Catagory
        </h2>

        <div class="row row-cols-1 row-cols-md-2 g-4">
            <div class="col">
                <div class="card">

                    <div class="card-body">
                        <a href="/product" class="btn btn-danger btn-lg">

                            All
                        </a>

                    </div>
                </div>
            </div>
            {%for i in cta%}
            <div class="col">
                <div class="card">

                    <div class="card-body">
                        <a href="/product?catagory={{i.id}}" class="btn btn-outline-info btn-lg">

                            <h3 class="card-title">{{i.name}}</h3>
                        </a>

                    </div>
                </div>
            </div>
            {%endfor%}

        </div>
    </div>

    <div class="container">
        <h2 style="background-color: rgb(6, 5, 5); color: rgb(135, 135, 76);text-align: center;height: 45px;">
            Here Your Product
        </h2>

        <div class="row row-cols-1 row-cols-md-2 g-4">
            {%for i in dt%}
            <div class="col">
                <div class="card">
                    <img src="{{i.pro_img.url}}" height="250" width="300" class="img-fluid" alt="...">
                    <div class="card-body">
                        <h2 class="card-title">Rs.{{i.price}}</h2>
                        <h3 class="card-title">{{i.pro_name}}</h3>
                        <p class="card-text">{{i.desc}}</p>
                        {%if user.is_authenticated%}
                        <form action="" method="post">
                            {%csrf_token%}

                            <a href="{%url 'cart:crt' i.id %}" class="btn btn-outline-info btn-lg">

                                <h3 class="card-title">Add To Cart</h3>

                            </a>

                            <a href="{%url 'product:buy_order' i.id %}" class="btn btn-outline-warning btn-lg">

                                <h3 class="card-title">Buy</h3>
                        </form>

                        </a>
                        {%endif%}


                    </div>
                </div>
            </div>
            {%endfor%}

user/templates/update.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Form</title>

</head>

<body>
    {%include 'nav.html'%}
   
    <h2 style="text-align: center;margin-top: 60px;">Profile Form</h2>
    <form action="" method="post" style="margin-top: 20px;">
        {%csrf_token%}
        <table class="d-flex justify-content-center align-items-center my-2 m">
            <tbody>
                <tr>
                </tr>
                <!-- <tr>
                    <th><label for="id_user" class="form-label">Username:</label></th>
                    <td>

                        <input type="text" class="form-control" name="user" class="form-control" required=""
                            id="id_user" fdprocessedid="67bbs" value="{{user}}">

                    </td>
                </tr> -->

                <!-- <tr>
                    <th><label for="id_profile_pic" class="form-label">Profile pic:</label></th>
                    <td>

                        <input type="file" class="form-control" name="profile_pic" accept="image/*" required=""
                            id="id_profile_pic">


                    </td>
                </tr> -->

                <tr>
                    <th><label for="id_first_name" class="form-label">First name:</label></th>
                    <td>

                        <input type="text" class="form-control" name="first_name" maxlength="70" required=""
                            id="id_first_name" fdprocessedid="ua23p">


                    </td>
                </tr>

                <tr>
                    <th><label for="id_Last_name" class="form-label">Last name:</label></th>
                    <td>

                        <input type="text" class="form-control" name="Last_name" maxlength="70" required=""
                            id="id_Last_name" fdprocessedid="r06wp4">


                    </td>
                </tr>

                <!-- <tr>
                    <th><label for="id_dob" class="form-label">Dob:</label></th>
                    <td>

                        <input type="text" class="form-control" name="dob" required="" id="id_dob"
                            fdprocessedid="g1icql">


                    </td>
                </tr> -->

                <tr>
                    <th><label for="id_email" class="form-label">Email:</label></th>
                    <td>

                        <input type="email" class="form-control" name="email" maxlength="70" required="" id="id_email"
                            fdprocessedid="fp5c8u">


                    </td>
                </tr>

                <tr>
                    <th><label for="id_address" class="form-label">Address:</label></th>
                    <td>

                        <input type="text" name="address" class="form-control" cols="40" rows="10" required=""
                            id="id_address">




                    </td>
                </tr>
                <tr>
                    <!-- <td>
                
                        <a href="/" class="btn btn-outline-danger  btn-lg  " tabindex="-1" role="button"
                            aria-disabled="true">Already Created</a>
                    </td> -->
                    <td>
                
                        <button type="submit" value="submit" class=" btn-outline-success my-4  btn-lg" style="margin-left: 30px;">Save Profile</button>
                    </td>
                
                </tr>

            </tbody>
        </table>
    </form>
    
</body>

</html>